domains = ["xgophers.com"]

[security]
certificates = [
    { certificate = "certs/xgophers.crt", key = "certs/private.der" }
]

[mailbox]
format = "maildir"

[mailbox.filesystem]
type = "local"
dir = "mail"

#[mailbox.filesystem]
#type = "s3"
#url = "..."

[imap]
enabled = false

[pop3]
enabled = true

[smtp.submission]
enabled = true

[smtp.transfer]
enabled = true